var pubs = [
  {
    'title':  'Generating Sports News from Live Commentary: A Chinese Dataset for Sports Game Summarization',
    'author': '<span class="text-hl">Kuan-Hao Huang</span>, Chen Li, and Kai-Wei Chang',
    'conf':   'Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics <span class="text-hl">(AACL)</span>, 2020',
    'url':    '',
  },
  {
    'title':  'Examining Gender Bias in Languages with Grammatical Gender',
    'author': 'Pei Zhou, Weijia Shi, Jieyu Zhao, <span class="text-hl">Kuan-Hao Huang</span>, Muhao Chen, Ryan Cotterell, and Kai-Wei Chang',
    'conf':   'Conference on Empirical Methods in Natural Language Processing <span class="text-hl">(EMNLP)</span>, 2019',
    'url':    'docs/emnlp2019bias.pdf',
    'code':   'https://github.com/shaoxia57/Bias_in_Gendered_Languages',
  },
  {
    'title':  'JECL: Joint Embedding and Cluster Learning for Image-Text Pairs',
    'author': 'Sean T. Yang, <span class="text-hl">Kuan-Hao Huang</span>, Bill Howe',
    'conf':   'Preprint arXiv:1901.01860, 2019',
    'url':    'https://arxiv.org/abs/1901.01860',
  },
  {
    'title':  'Dynamic Principal Projection for Cost-Sensitive Online Multi-Label Classification',
    'author': 'Hong-Min Chu, <span class="text-hl">Kuan-Hao Huang</span>, and Hsuan-Tien Lin',
    'conf':   'Machine Learning <span class="text-hl">(ECML PKDD Journal Track)</span>, 2019',
    'url':    'docs/ecml2019csdpp.pdf',
  },
  {
    'title':  'Cost-Sensitive Reference Pair Encoding for Multi-Label Learning',
    'author': 'Yao-Yuan Yang, <span class="text-hl">Kuan-Hao Huang</span>, Chih-Wei Chang, and Hsuan-Tien Lin',
    'conf':   'Pacific-Asia Conference on Knowledge Discovery and Data Mining <span class="text-hl">(PAKDD)</span>, 2018',
    'url':    'docs/pakdd2018csrpe.pdf',
    'code':   'https://github.com/yangarbiter/multilabel-learn/blob/master/mlearn/models/csrpe.py',
  },
  {
    'title':  'Cost-Sensitive Label Embedding for Multi-Label Classification',
    'author': '<span class="text-hl">Kuan-Hao Huang</span> and Hsuan-Tien Lin',
    'conf':   'Machine Learning <span class="text-hl">(ECML PKDD Journal Track)</span>, 2017',
    'url':    'docs/ecml2017clems.pdf',
    'code':   'https://github.com/ej0cl6/csmlc',
    'slides': 'docs/ecml2017clems_handout.pdf',
    'poster': 'docs/ecml2017clems_poster.pdf',
  },
  {
    'title':  'A Novel Uncertainty Sampling Algorithm for Cost-Sensitive Multiclass Active Learning',
    'author': '<span class="text-hl">Kuan-Hao Huang</span> and Hsuan-Tien Lin',
    'conf':   'IEEE International Conference on Data Mining <span class="text-hl">(ICDM)</span>, 2016',
    'url':    'docs/icdm2016alce.pdf',
    'code':   'https://github.com/ej0cl6/csmcal',
    'slides': 'docs/icdm2016alce_handout.pdf',
  },
  {
    'title':  'Linear Upper Confidence Bound Algorithm for Contextual Bandit Problem with Piled Rewards',
    'author': '<span class="text-hl">Kuan-Hao Huang</span> and Hsuan-Tien Lin',
    'conf':   'Pacific-Asia Conference on Knowledge Discovery and Data Mining <span class="text-hl">(PAKDD)</span>, 2016',
    'url':    'docs/pakdd2016linucbpr.pdf',
    'code':   'https://github.com/ej0cl6/cbpr',
    'slides': 'docs/pakdd2016linucbpr_handout.pdf',
  },
  {
    'title':  'Combination of Feature Engineering and Ranking Models for Paper-Author Identification in KDD Cup 2013',
    'author': 'Chun-Liang Li, Yu-Chuan Su, Ting-Wei Lin, Cheng-Hao Tsai, Wei-Cheng Chang, <span class="text-hl">Kuan-Hao Huang</span>, Tzu-Ming Kuo, Shan-Wei Lin, Young-San Lin, Yu-Chen Lu, Chun-Pai Yang, Cheng-Xia Chang, Wei-Sheng Chin, Yu-Chin Juan, Hsiao-Yu Tung, Jui-Pin Wang, Cheng-Kuang Wei, Felix Wu, Tu-Chun Yin, Tong Yu, Yong Zhuang, Shou-de Lin, Hsuan-Tien Lin, and Chih-Jen Lin',
    'conf':   'Journal of Machine Learning Research <span class="text-hl">(JMLR)</span>, 2015',
    'url':    'docs/kdd2013cup_track1.pdf',
    'code':   'https://github.com/kdd-cup-2013-ntu/track1',
  },
  {
    'title':  'Effective String Processing and Matching for Author Disambiguation',
    'author': 'Wei-Sheng Chin, Yu-Chin Juan, Yong Zhuang, Felix Wu, Hsiao-Yu Tung, Tong Yu, Jui-Pin Wang, Cheng-Xia Chang, Chun-Pai Yang, Wei-Cheng Chang, <span class="text-hl">Kuan-Hao Huang</span>, Tzu-Ming Kuo, Shan-Wei Lin, Young-San Lin, Yu-Chen Lu, Yu-Chuan Su, Cheng-Kuang Wei, Tu-Chun Yin, Chun-Liang Li, Ting-Wei Lin, Cheng-Hao Tsai, Shou-de Lin, Hsuan-Tien Lin, and Chih-Jen Lin',
    'conf':   'Journal of Machine Learning Research <span class="text-hl">(JMLR)</span>, 2014',
    'url':    'docs/kdd2013cup_track2.pdf',
    'code':   'https://github.com/kdd-cup-2013-ntu/track2',
  },
];
